### ISSUE TITLE
set_readonly RPC is broken

### ISSUE THREAD

**Issue by troggy** [parsec-labs/tendermint#3]
to reproduce:
- start the validator with `--readonly --unsafeRpc`
- call `curl 'http://localhost:26659/set_readonly?readonly=false'`
- it should start producing blocks, but it is not

Side note: this flow was working before the latest upgrade

**Comment by pinkiebell** [comment]
Investigating...

**Comment by pinkiebell** [comment]
Linking https://github.com/tendermint/tendermint/issues/3341
